<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gohtml</string>
	</array>
	<key>name</key>
	<string>GoRazor</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;text&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.textblock.gohtml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>&lt;text&gt;&lt;/text&gt; content tags</string>
			<key>end</key>
			<string>(&lt;/text&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.textblock.gohtml</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\&lt;head\&gt;|\&lt;html\&gt;|\&lt;body\&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.special.opening.gohtml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>special html tags</string>
			<key>end</key>
			<string>((\&lt;/head\&gt;|\&lt;/html\&gt;|\&lt;/body\&gt;))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.special.closing.gohtml</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\&lt;[a-zA-Z0-9]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.begin.html.gohtml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>handle gohtml inside html</string>
			<key>end</key>
			<string>(\&lt;)?(/)([a-zA-Z0-9\-]+)?(\&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.end.html.gohtml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.end.slash.html.gohtml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.end.html.gohtml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.end.html.gohtml</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>attribute</string>
					<key>match</key>
					<string>([a-zA-Z0-9\-]+\=)(?=[\'\"\@])</string>
					<key>name</key>
					<string>entity.name.attribute.gohtml</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\=)(\')</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single.gohtml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>single quotes</string>
					<key>end</key>
					<string>(\')</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single.gohtml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>text.basic.gohtml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>string.quoted.single.gohtml</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\=)(\")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.gohtml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>double quotes</string>
					<key>end</key>
					<string>(\")</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.gohtml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>text.basic.gohtml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>string.quoted.double.gohtml</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.begin.closing.gohtml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>innerHTML</string>
					<key>end</key>
					<string>(\&lt;[a-zA-Z0-9]*)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.end.opeing.gohtml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>swallow quotes</string>
					<key>match</key>
					<string>\'|\"</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.go</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.gohtml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>code block</string>
			<key>contentName</key>
			<string>source.go</string>
			<key>end</key>
			<string>^[\t ]*\}$</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.class.gohtml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.go</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.go</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@)?((if|for|switch|section) )([^\{\n]+)(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.gohtml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.go</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>source.go</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.class.gohtml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>transition brace</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.class.gohtml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.go</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.go</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@\*)</string>
			<key>comment</key>
			<string>Multi-line Comments</string>
			<key>end</key>
			<string>(\*@)</string>
			<key>name</key>
			<string>comment.line.gohtml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Escaped transition character</string>
			<key>match</key>
			<string>@@</string>
			<key>name</key>
			<string>string.regexp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.gohtml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>\@(variable expression)</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.gohtml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.go</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\@)([a-zA-Z\.]+)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.gohtml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.gohtml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.class.gohtml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>\@module.func(....)</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.gohtml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>module.func</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comma</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\@)([a-zA-Z\.]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.gohtml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.gohtml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>\@variable</string>
			<key>end</key>
			<string>(\b)</string>
			<key>name</key>
			<string>source.go</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>source.go</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>code block</string>
			<key>contentName</key>
			<string>source.go</string>
			<key>end</key>
			<string>^[\t ]*\}[\t ]*$</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>source.go</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.go</string>
				</dict>
			</array>
		</dict>
		<key>comma</key>
		<dict>
			<key>match</key>
			<string>([, ]+)</string>
			<key>name</key>
			<string>punctuation.definition.comma.go</string>
		</dict>
		<key>function</key>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z]+)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.go</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comma</string>
				</dict>
			</array>
		</dict>
		<key>method</key>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z]+).([a-zA-Z]+)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.gohtml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.go</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.gohtml</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>(\")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.gohtml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\")</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.gohtml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>text.basic.gohtml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.quoted.double.gohtml</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>match</key>
			<string>([a-zA-Z]+)</string>
			<key>name</key>
			<string>variable.other.go</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.gohtml</string>
	<key>uuid</key>
	<string>65e21840-02e5-11e4-9191-0800200c9a66</string>
</dict>
</plist>
